# Homework 6


## EMNIST Dataset

[EMNIST dataset](https://www.nist.gov/itl/iad/image-group/emnist-dataset) is a set of hand-written characters and digits. Each of the data points is a grayscale image of size 28x28 pixels.  The structure of the dataset is the same as the infamous [MNIST](http://yann.lecun.com/exdb/mnist/) dataset, but this dataset contains more samples and also contains characters. You can find more information on the dataset in the paper available at [https://arxiv.org/abs/1702.05373v1](https://arxiv.org/abs/1702.05373v1)

You can find the dataset you need [at this link](https://www.dropbox.com/sh/vgap8ici7xs5w7f/AACE-9RrDpbGCc6bP72gHRfUa?dl=0).  Please download and use your local copy to do the homework.

## Task 1

Ingest the data (both the train and test sets) into this pyhthon notebook as a numpy array.


## Task 2

Write a convolutional artifial neural network model, train it and test it.


## Notes

1. You need to document each of your steps in both the ingestion phase and processing phase: explain the steps taken, the problems you encounter, how you solved them.

2. DO NOT write python classes.  In other words, I do not want to see `__init__` or `__main__` in your code.  They are hard to follow (as they contain mutable state) and hard to port to future code you might write on a similar project.

3. When you upload your solution to github, DO NOT include the datasets. They are large and I already have copies. I can test your models on the copy I have.

In [49]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import Normalizer

from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, Conv1D, Conv2D, Flatten, MaxPooling2D
from keras.optimizers import Adam, Adamax, RMSprop, SGD

import keras.backend as K
import keras as keras

In [50]:
from mlxtend.data import loadlocal_mnist

x_train, y_train = loadlocal_mnist(images_path = '/Users/furkanhatipoglu/Desktop/EMNIST/emnist-balanced-train-images-idx3-ubyte', labels_path = '/Users/furkanhatipoglu/Desktop/EMNIST/emnist-balanced-train-labels-idx1-ubyte')
x_test, y_test = loadlocal_mnist(images_path = '/Users/furkanhatipoglu/Desktop/EMNIST/emnist-balanced-test-images-idx3-ubyte', labels_path = '/Users/furkanhatipoglu/Desktop/EMNIST/emnist-balanced-test-labels-idx1-ubyte')
print(x_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [51]:
y_train = keras.utils.to_categorical(y_train)

# Sequential model objesi yaratalım
model = Sequential()
# Modelimize bir 2 boyutlu Convolutional katman(layer) ekleyelim.
model.add(Conv2D(64, (4,4), input_shape=(28,28,1,), activation='tanh'))
# Keras’ın Dense layer tipinde yapay sinir agi olusturalim.
model.add(Dense(32,activation='relu'))
# Weightleri ceyregine düşüren bir Droput katmanı ekliyoruz.Neural Network’lerde overfitting’i engellemek için icat edilmiş basit bir yöntem
model.add(Dropout(0.25))
# MaxPooling işlemi, verimizden, verilen pool_size boyutunda kümeler alıp bu kümeler içerisindeki en büyük değerleri kullanarak yeni bir matris oluşturur.
model.add(MaxPooling2D(pool_size=(2,2)))
# Genellikle Convolutional bölümün sonuna konan Flatten metodu çok boyutlu olan verimizi tek boyutlu hale getirerek standart yapay sinir ağı için hazır hale getirir.
model.add(Flatten())
# Farkli bir activation yapay sinir agi olusturalim tekrar
model.add(Dense(47, activation='sigmoid'))
# Weightleri tekrar dusurelim
model.add(Dropout(0.05))
# modelimizi compile edelim
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='RMSProp')
# ve modelimizi kullanalim 
model.fit(x_train.reshape(len(x_train),28,28,1), y_train, batch_size=512, epochs=10)

Epoch 1/10
112800/112800 [==============================] - 86s 762us/step - loss: 1.6831 - acc: 0.6901
Epoch 2/10
112800/112800 [==============================] - 85s 757us/step - loss: 1.2570 - acc: 0.7982
Epoch 3/10
112800/112800 [==============================] - 85s 751us/step - loss: 1.2142 - acc: 0.8160
Epoch 4/10
112800/112800 [==============================] - 84s 748us/step - loss: 1.1744 - acc: 0.8285
Epoch 5/10
112800/112800 [==============================] - 84s 749us/step - loss: 1.1509 - acc: 0.8370
Epoch 6/10
112800/112800 [==============================] - 83s 737us/step - loss: 1.1113 - acc: 0.8446
Epoch 7/10
112800/112800 [==============================] - 88s 777us/step - loss: 1.1011 - acc: 0.8491
Epoch 8/10
112800/112800 [==============================] - 88s 776us/step - loss: 1.0786 - acc: 0.8540
Epoch 9/10
112800/112800 [==============================] - 88s 777us/step - loss: 1.0725 - acc: 0.8563
Epoch 10/10
112800/112800 [==============================] - 96s